# Generated by Django 4.1 on 2023-07-28 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Form_Meta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100)),
                ('form_description', models.CharField(max_length=160)),
                ('form_country', models.CharField(max_length=40)),
                ('form_field', models.CharField(max_length=80)),
                ('form_status', models.CharField(choices=[('deployed', 'Deployed'), ('draft', 'Draft'), ('arquived', 'Arquived')], max_length=100)),
            ],
        ),
    ]
