# Generated by Django 4.1 on 2023-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_project_form_meta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_form_meta',
            name='form_name',
            field=models.CharField(max_length=80),
        ),
    ]
