# Generated by Django 4.1 on 2023-08-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_project_form_meta_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_form',
            name='field_size',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Form_Sql_Query_Db',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sql_query', models.TextField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('form_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.project_form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
