# Generated by Django 4.1 on 2023-08-20 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_alter_project_form_field_size_form_sql_query_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_form',
            name='field_label',
            field=models.CharField(default='Label', max_length=80),
        ),
        migrations.AlterField(
            model_name='form_sql_query_db',
            name='form_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.project_form_meta'),
        ),
        migrations.CreateModel(
            name='FieldwithChoiceOptions',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=160)),
                ('option_label', models.CharField(max_length=160)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('project_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.project_form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
