# Generated by Django 4.1 on 2023-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_project_form_field_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_form_meta',
            name='form_status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=100),
        ),
    ]
