# Generated by Django 4.1 on 2023-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_project_form_meta_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldwithchoiceoptions',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldwithchoiceoptions',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='form_sql_query_db',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='form_sql_query_db',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_form',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_form',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
