# Generated by Django 4.1 on 2023-10-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0008_alter_fieldwithchoiceoptions_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Form_Shared',
            fields=[
                ('created_date', models.DateField(null=True)),
                ('updated_date', models.DateField(null=True)),
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_form', models.BooleanField(default=False)),
                ('edit_form', models.BooleanField(default=False)),
                ('form_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.project_form_meta')),
                ('project_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.project_form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
