# Generated by Django 4.1 on 2023-10-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_project_form_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_form_shared',
            name='project_form',
        ),
    ]
