# Generated by Django 4.1 on 2023-10-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_remove_project_form_shared_project_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_form_shared',
            old_name='user',
            new_name='shared_with_user',
        ),
    ]
